
services:
  app:
    image: ecommerce_php
    build: .
    container_name: ecommerce_uoc
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - ecommerce_network
    ports:
      - "9000:9000"
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: php_webserver
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - ecommerce_network

  db:
    image: mysql:8.0
    container_name: php_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      #- db/data:/var/lib/mysql
      #- ./database/conf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./db/scripts:/docker-entrypoint-initdb.d:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3310:3306"
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

# volumes:
#   dbdata:
#     driver: local
